# Generated by Django 4.2 on 2024-11-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
