# Generated by Django 4.2 on 2024-11-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stripe_pid",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
