# Generated by Django 4.2 on 2024-11-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0004_order_stripe_pid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="grand_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
