# Generated by Django 5.1.2 on 2024-10-23 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_order_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='available_stock',
        ),
    ]
