# Generated by Django 4.2 on 2024-11-17 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('basket', '0002_alter_basketitem_cake'),
        ('home', '0007_alter_cake_image_alter_cake_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='cake',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cake',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='cake',
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.product'),
        ),
        migrations.AddField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='products.product'),
        ),
        migrations.DeleteModel(
            name='Cake',
        ),
    ]
