# Generated by Django 4.2 on 2024-11-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_customer_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="address",
        ),
        migrations.AddField(
            model_name="customer",
            name="county",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="postcode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="street_address1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="street_address2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="town_or_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
