# Generated by Django 4.2 on 2024-11-17 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='cake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.cake'),
        ),
    ]
