# Generated by Django 4.2 on 2025-02-23 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_remove_customcake_custom_message_and_more"),
        ("basket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketitem",
            name="custom_cake",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.customcake",
            ),
        ),
        migrations.AlterField(
            model_name="basketitem",
            name="cake",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.cake",
            ),
        ),
    ]
