# Generated by Django 4.2 on 2025-03-22 00:53

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CakeSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("product", "Product Category"),
                            ("customization", "Customization Category"),
                        ],
                        default="product",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Filling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Flavour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Flavours",
            },
        ),
        migrations.CreateModel(
            name="Frosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("cake", "Cake"),
                            ("custom_cake", "Custom Cake"),
                            ("cupcake", "Cupcake"),
                            ("accessory", "Accessory"),
                        ],
                        default="cake",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Accessory",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="products.product",
                    ),
                ),
                (
                    "accessory_type",
                    models.CharField(
                        choices=[
                            ("candles", "Candles"),
                            ("toppers", "Cake Toppers"),
                            ("banners", "Banners"),
                            ("balloons", "Balloons"),
                        ],
                        default="candles",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Accessories",
            },
            bases=("products.product",),
        ),
        migrations.CreateModel(
            name="Cake",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="products.product",
                    ),
                ),
                (
                    "occasion",
                    models.CharField(
                        choices=[
                            ("wedding", "Wedding"),
                            ("birthday", "Birthday"),
                            ("anniversary", "Anniversary"),
                            ("baby_shower", "Baby Shower"),
                            ("gender_reveal", "Gender Reveal"),
                            ("communion", "Communion"),
                            ("confirmation", "Confirmation"),
                            ("christening", "Christening"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=50, null=True)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("toppers_allowed", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
            bases=("products.product",),
        ),
        migrations.CreateModel(
            name="CustomCake",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="products.product",
                    ),
                ),
                ("custom_message", models.BooleanField(default=False)),
                (
                    "inscription",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("toppers", models.JSONField(blank=True, default=list, null=True)),
                (
                    "filling",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.filling",
                    ),
                ),
                (
                    "flavour",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.flavour",
                    ),
                ),
                (
                    "frosting",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.frosting",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.cakesize",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
            bases=("products.product",),
        ),
        migrations.CreateModel(
            name="Cupcake",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="products.product",
                    ),
                ),
                ("custom_message", models.BooleanField(default=False)),
                (
                    "flavour",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.flavour",
                    ),
                ),
                (
                    "frosting",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.frosting",
                    ),
                ),
            ],
            bases=("products.product",),
        ),
    ]
