# Generated by Django 4.2 on 2024-12-01 04:28

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "product_type",
                    models.CharField(
                        choices=[("cake", "Cake")], default="cake", max_length=50
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Cake",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="products.product",
                    ),
                ),
                (
                    "occasion",
                    models.CharField(
                        choices=[
                            ("wedding", "Wedding"),
                            ("birthday", "Birthday"),
                            ("anniversary", "Anniversary"),
                            ("baby_shower", "Baby Shower"),
                            ("gender_reveal", "Gender Reveal"),
                            ("communion", "Communion"),
                            ("confirmation", "Confirmation"),
                            ("christening", "Christening"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
            bases=("products.product",),
        ),
        migrations.CreateModel(
            name="CustomCake",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="products.product",
                    ),
                ),
                (
                    "flavor",
                    models.CharField(
                        choices=[
                            ("vanilla", "Vanilla"),
                            ("chocolate", "Chocolate"),
                            ("red_velvet", "Red Velvet"),
                            ("lemon", "Lemon"),
                            ("carrot", "Carrot"),
                        ],
                        default="vanilla",
                        max_length=50,
                    ),
                ),
                (
                    "filling",
                    models.CharField(
                        choices=[
                            ("chocolate", "Chocolate"),
                            ("buttercream", "Buttercream"),
                            ("raspberry", "Raspberry"),
                            ("lemon", "Lemon"),
                            ("cream_cheese", "Cream Cheese"),
                        ],
                        default="buttercream",
                        max_length=50,
                    ),
                ),
                (
                    "inscription",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "ordering": ["name"],
            },
            bases=("products.product",),
        ),
    ]
