# Generated by Django 4.2 on 2025-02-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="allergens",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_gluten_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_vegan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="num_reviews",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
