# Generated by Django 4.2 on 2025-02-20 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_allergens_product_is_gluten_free_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accessory",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="products.product",
                    ),
                ),
                (
                    "accessory_type",
                    models.CharField(
                        choices=[
                            ("candles", "Candles"),
                            ("toppers", "Cake Toppers"),
                            ("banners", "Banners"),
                            ("balloons", "Balloons"),
                        ],
                        default="candles",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
            bases=("products.product",),
        ),
    ]
