# Generated by Django 4.2 on 2024-11-18 20:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_related_name_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
