# Generated by Django 4.2 on 2025-02-22 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_accessory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accessory",
            options={"verbose_name_plural": "Accessories"},
        ),
    ]
