# Generated by Django 4.2 on 2025-02-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_accessory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
