# Generated by Django 4.2 on 2024-11-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_options_remove_category_related_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='occasion',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('baby_shower', 'Baby Shower'), ('gender_reveal', 'Gender Reveal'), ('Communion', 'Communion'), ('Confirmation', 'Confirmation'), ('Christening', 'Christening'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
