# Generated by Django 4.2 on 2025-02-23 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="color",
        ),
        migrations.AddField(
            model_name="customcake",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customcake",
            name="custom_message",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[("cake", "Cake"), ("accessory", "Accessory")],
                default="cake",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Cupcake",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="products.product",
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("custom_message", models.BooleanField(default=False)),
                (
                    "flavor",
                    models.CharField(
                        choices=[
                            ("vanilla", "Vanilla"),
                            ("chocolate", "Chocolate"),
                            ("red_velvet", "Red Velvet"),
                            ("lemon", "Lemon"),
                            ("carrot", "Carrot"),
                        ],
                        default="vanilla",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
            bases=("products.product",),
        ),
    ]
