# Generated by Django 4.2 on 2025-02-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_remove_product_color_customcake_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customcake",
            name="custom_message",
        ),
        migrations.RemoveField(
            model_name="product",
            name="allergens",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_gluten_free",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_vegan",
        ),
        migrations.RemoveField(
            model_name="product",
            name="num_reviews",
        ),
        migrations.RemoveField(
            model_name="product",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
        migrations.AddField(
            model_name="cake",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cake",
            name="size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cake",
            name="toppers_allowed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customcake",
            name="size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customcake",
            name="toppers",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.DeleteModel(
            name="Cupcake",
        ),
    ]
