# Generated by Django 4.2 on 2024-11-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_cake_occasion"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[("cake", "Cake"), ("cupcake", "Cupcake")],
                default="cake",
                max_length=50,
            ),
        ),
    ]
