# Generated by Django 4.2 on 2024-11-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_product_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cake",
            name="occasion",
            field=models.CharField(
                choices=[
                    ("wedding", "Wedding"),
                    ("birthday", "Birthday"),
                    ("anniversary", "Anniversary"),
                    ("baby_shower", "Baby Shower"),
                    ("gender_reveal", "Gender Reveal"),
                    ("Communion", "Communion"),
                    ("Confirmation", "Confirmation"),
                    ("Christening", "Christening"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="preview_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[("cake", "Cake"), ("cupcake", "Cupcake"), ("other", "Other")],
                default="cake",
                max_length=50,
            ),
        ),
    ]
