# Generated by Django 4.2 on 2025-02-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_remove_customcake_custom_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customcake",
            name="custom_message",
            field=models.BooleanField(default=False),
        ),
    ]
