# Generated by Django 4.2 on 2024-11-22 14:24

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_cake_occasion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomCake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flavor",
                    models.CharField(
                        choices=[
                            ("vanilla", "Vanilla"),
                            ("chocolate", "Chocolate"),
                            ("red_velvet", "Red Velvet"),
                            ("lemon", "Lemon"),
                            ("carrot", "Carrot"),
                        ],
                        default="vanilla",
                        max_length=50,
                    ),
                ),
                (
                    "filling",
                    models.CharField(
                        choices=[
                            ("chocolate", "Chocolate"),
                            ("buttercream", "Buttercream"),
                            ("raspberry", "Raspberry"),
                            ("lemon", "Lemon"),
                            ("cream_cheese", "Cream Cheese"),
                        ],
                        default="buttercream",
                        max_length=50,
                    ),
                ),
                (
                    "inscription",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
            ],
        ),
    ]
