# Generated by Django 4.2 on 2025-02-23 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_product_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cupcake",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="products.product",
                    ),
                ),
                ("flavor", models.CharField(max_length=50)),
                ("filling", models.CharField(blank=True, max_length=50, null=True)),
                ("custom_message", models.BooleanField(default=False)),
            ],
            bases=("products.product",),
        ),
    ]
