# Generated by Django 4.2 on 2024-11-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_customcake"),
    ]

    operations = [
        migrations.AddField(
            model_name="customcake",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
