# Generated by Django 4.2 on 2024-11-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_customcake_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="CakeSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name="cake",
            name="sizes",
            field=models.ManyToManyField(related_name="cakes", to="products.cakesize"),
        ),
        migrations.AddField(
            model_name="customcake",
            name="sizes",
            field=models.ManyToManyField(
                blank=True, related_name="custom_cakes", to="products.cakesize"
            ),
        ),
    ]
