# Generated by Django 4.2 on 2025-03-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_cupcake"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("cake", "Cake"),
                    ("custom_cake", "Custom Cake"),
                    ("cupcake", "Cupcake"),
                    ("accessory", "Accessory"),
                ],
                default="cake",
                max_length=50,
            ),
        ),
    ]
