# Generated by Django 4.2 on 2024-11-30 23:20

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_cakesize_cake_sizes_customcake_sizes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accessory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "accessory_type",
                    models.CharField(
                        choices=[("candles", "Candles"), ("toppers", "Toppers")],
                        default="candles",
                        max_length=50,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessories",
                        to="products.category",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="cake",
            name="sizes",
        ),
        migrations.RemoveField(
            model_name="customcake",
            name="sizes",
        ),
        migrations.RemoveField(
            model_name="product",
            name="preview_description",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="products.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[("cake", "Cake"), ("accessory", "Accessory")],
                default="cake",
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="CakeSize",
        ),
    ]
