# Generated by Django 4.2 on 2024-11-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_cakesize_cake_sizes_customcake_sizes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cake",
            name="occasion",
            field=models.CharField(
                choices=[
                    ("wedding", "Wedding"),
                    ("birthday", "Birthday"),
                    ("anniversary", "Anniversary"),
                    ("baby_shower", "Baby Shower"),
                    ("gender_reveal", "Gender Reveal"),
                    ("communion", "Communion"),
                    ("confirmation", "Confirmation"),
                    ("christening", "Christening"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
