# Generated by Django 4.2 on 2024-11-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_cake_occasion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cakesize",
            name="name",
            field=models.CharField(
                choices=[
                    ("8_inch_round", "8 inch Round"),
                    ("10_inch_round", "10 inch Round"),
                    ("12_inch_round", "12 inch Round"),
                    ("8_inch_square", "8 inch Square"),
                    ("10_inch_square", "10 inch Square"),
                    ("12_inch_square", "12 inch Square"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
